# Configuration for Austria Water Integration
# This file defines the cooling technology integration for Austria

# Project metadata
project:
  name: "water_austria"
  version: "0.1.0"
  description: "Cooling technology integration for Austria energy system"

# Geographic scope
geography:
  base_region: "Austria"

# Cooling technology implementation
cooling:
  description: "Power plant cooling technologies"
  cooling_types:
    - "ot_fresh"     # Once-through freshwater
    - "cl_fresh"     # Closed-loop freshwater  
    - "air"          # Air cooling
    - "ot_saline"    # Once-through saline
  water_commodities:
    - "freshwater"
    - "surfacewater_basin"
    - "salinewater_basin"
    - "ot_fresh"
    - "cl_fresh"
  water_levels:
    - "water_supply"
    - "water_avail_basin"
    - "saline_supply"
  supply_technologies:
    - "extract_surfacewater"
    - "extract_salinewater"
    - "water_supply_austria"